export const CONNECT = 'CONNECT'
export const CONNECTION = 'CONNECTION'

export const OPERATIONS_RECEIVE = 'OPERATIONS_RECEIVE'
export const REPLICA_INFO_RECEIVE = 'REPLICA_INFO_RECEIVE'
export const DATABASE_INFO_RECEIVE = 'DATABASE_INFO_RECEIVE'
